drop table if exists USERS;
drop table if exists PERSONS;

CREATE TABLE USERS(
	USER_ID      INT NOT NULL AUTO_INCREMENT,
	USER_NAME    VARCHAR(30) NOT NULL,
	FIRST_NAME   VARCHAR(30) NOT NULL,
	LAST_NAME    VARCHAR(30) NOT NULL,
	EMAIL        VARCHAR(30) NULL,
	CREATE_USERID    INT,
	CREATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
	UPDATE_USERID    INT,
	UPDATE_TIMESTAMP TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY(USER_ID)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;


CREATE TABLE PERSONS (
  PERSON_ID   INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME  VARCHAR(30) NOT NULL,
  LAST_NAME   VARCHAR(30) NOT NULL,
  PRIMARY KEY(PERSON_ID)  
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;   


